### ISSUE TITLE
ModuleNotFoundError: No module named 'speechbrain.pretrained'

### ISSUE THREAD

**Issue by inv-adityamanoj** [NavodPeiris/speechlib#20]
i tried to run the example file given in the readme on git and followed the instructions for the voice_folders but when i try to run it i get the error 
`ModuleNotFoundError: No module named 'speechbrain.pretrained'`

We made sure speechbrain is pip installed.
Tried to uninstall and reinstall.
And tried to upgrade the speechbrain package too.

Am i missing something here?

**Comment by NavodPeiris** [comment]
thanks for the issue. Speechbrain has updated to version 1.0.0 where it has updated the way modules are imported. however, still version 1.0.0 is not compatible with pyannote.audio 3.1.1 so we should stick with old speechbrain for now. 
I actually forgot to set the versions of the dependencies. that is why all dependencies are updated to latest version. i will patch the issue.

**Comment by NavodPeiris** [comment]
I have used speechbrain==0.5.16 in the latest release of speechlib. now it is running as intended.

**Comment by inv-adityamanoj** [comment]
Will give that a try. Thank you so much!

**Comment by nobodyz** [comment]
Ran into the same error, it seems like the fix is quite simple in speechlib as well. The imports in speechlib have to be changed from speechbrain.pretrained to speechbrain.inference (speaker_identification.py and speaker_recognition.py). Have not done any testing apart from the supplied example scripts, but those worked after the changes.

**Comment by Waxolunist** [comment]
@nobodyz Did you use 1.0.0 or 0.5.16 of speechbrain?
